apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "camunda-optimize.labels" . | nindent 4 }}
  name: optimize-cert
stringData:
  cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIIF7TCCBNWgAwIBAgIQAZmTO50lRUiZk2Y ... <<your cert here>>
    -----END CERTIFICATE-----